wandb_resume: allow
wandb_project_name: state-tracking
wandb_entity: null
wandb_group: null
run_name: ${data.group}-${model.model_type}-lr_${trainer.lr}-pe_${model.position_embedding.type}-${trainer.seed}
